//This file is automatically generated.
//Do not attempt to make changes to this file because the changes will be erased and overwritten.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using DataConnectionBase;

namespace SparksBrainUploader.Crud{
	public class PrefCrud {
		///<summary>Gets one Pref object from the database using a query.</summary>
		public static Pref SelectOne(string command) {
			List<Pref> listPrefs=TableToList(Db.GetTable(command));
			if(listPrefs.Count==0) {
				return null;
			}
			return listPrefs[0];
		}

		///<summary>Gets a list of Pref objects from the database using a query.</summary>
		public static List<Pref> SelectMany(string command) {
			List<Pref> listPrefs=TableToList(Db.GetTable(command));
			return listPrefs;
		}

		///<summary>Converts a DataTable to a list of objects.</summary>
		public static List<Pref> TableToList(DataTable table) {
			List<Pref> listPrefs=new List<Pref>();
			for(int i=0;i<table.Rows.Count;i++) {
				Pref pref=new Pref();
				pref.PrefNum    = SIn.Int   (table.Rows[i]["PrefNum"].ToString());
				pref.PrefName   = SIn.String(table.Rows[i]["PrefName"].ToString());
				pref.ValueString= SIn.String(table.Rows[i]["ValueString"].ToString());
				listPrefs.Add(pref);
			}
			return listPrefs;
		}

		///<summary>Inserts one Pref into the database.  Returns the new priKey.</summary>
		public static long Insert(Pref pref) {
			string command="INSERT INTO pref (PrefName,ValueString) VALUES("
				+"'"+SOut.String(pref.PrefName)+"',"
				+"'"+SOut.String(pref.ValueString)+"')";
				pref.PrefNum=Db.NonQ(command,true);
			return pref.PrefNum;
		}

		///<summary>Updates one Pref in the database.</summary>
		public static void Update(Pref pref) {
			string command="UPDATE pref SET "
				+"PrefName   = '"+SOut.String(pref.PrefName)+"', "
				+"ValueString= '"+SOut.String(pref.ValueString)+"' "
				+"WHERE PrefNum = "+SOut.Int(pref.PrefNum);
			Db.NonQ(command);
		}
	}
}