using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using SparksBrainUploader;

namespace CrudGenerator {
	public partial class Form1:Form {
		public static string crudDir=@"..\..\..\Crud";
		private const string rn="\r\n";
		private const string t="\t";
		private const string t2="\t\t";
		private const string t3="\t\t\t";
		private const string t4="\t\t\t\t";
		private const string t5="\t\t\t\t\t";
		private const string t6="\t\t\t\t\t\t";
		private const string t7="\t\t\t\t\t\t\t";

		public Form1() {
			InitializeComponent();
		}

		private void buttonGenerate_Click(object sender,EventArgs e) {
			//bool exists=Directory.Exists(crudDir);
			//string dir=Environment.CurrentDirectory;
			//return;
			List<Type> listTypes=new List<Type>();
			//Add the types manually here
			listTypes.Add(typeof(Pref));
			for(int i=0;i<listTypes.Count;i++){
				#region Variables
				List<FieldInfo> listFieldInfos=listTypes[i].GetFields().ToList();
				listFieldInfos=listFieldInfos.FindAll(delegate(FieldInfo fieldInfo){
					List<Attribute> listAttributes = fieldInfo.GetCustomAttributes(typeof(CrudColumnAttribute)).ToList();
					if(listAttributes.Count==0){
						return false;//exclude the fields with no Idx
					}
					return true;
				});
				listFieldInfos=listFieldInfos.OrderBy(delegate(FieldInfo fieldInfo) {
					List<Attribute> listAttributes = fieldInfo.GetCustomAttributes(typeof(CrudColumnAttribute)).ToList();
					return ((CrudColumnAttribute)listAttributes[0]).Idx;
				}).ToList();
				string obj=listTypes[i].Name.Substring(0,1).ToLower()+listTypes[i].Name.Substring(1);//lowercase initial letter.  Example feeSched
				#endregion Variables
				#region class header
				StringBuilder stringBuilder =new StringBuilder();
				stringBuilder.Append(@"//This file is automatically generated.
//Do not attempt to make changes to this file because the changes will be erased and overwritten.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using DataConnectionBase;

namespace SparksBrainUploader.Crud{
	public class "+listTypes[i].Name+@"Crud {");
				#endregion class header
				#region SelectOne
				//SelectOne(string command)--------------------------------------------------------------------------
				stringBuilder.Append(rn+t2+"///<summary>Gets one "+listTypes[i].Name+" object from the database using a query.</summary>");
				stringBuilder.Append(rn+t2+"public static "+listTypes[i].Name+" SelectOne(string command) {");
				stringBuilder.Append(rn+t3+"List<"+listTypes[i].Name+"> list"+listTypes[i].Name+"s=TableToList(Db.GetTable(command));");
				stringBuilder.Append(rn+t3+"if(list"+listTypes[i].Name+"s.Count==0) {");
				stringBuilder.Append(rn+t4+"return null;");
				stringBuilder.Append(rn+t3+"}");
				stringBuilder.Append(rn+t3+"return list"+listTypes[i].Name+"s[0];");
				stringBuilder.Append(rn+t2+"}");
				#endregion SelectOne
				#region SelectMany
				//SelectMany-----------------------------------------------------------------------------------------
				stringBuilder.Append(rn+rn+t2+"///<summary>Gets a list of "+listTypes[i].Name+" objects from the database using a query.</summary>");
				stringBuilder.Append(rn+t2+"public static List<"+listTypes[i].Name+"> SelectMany(string command) {");
				stringBuilder.Append(rn+t3+"List<"+listTypes[i].Name+"> list"+listTypes[i].Name+"s=TableToList(Db.GetTable(command));");
				stringBuilder.Append(rn+t3+"return list"+listTypes[i].Name+"s;");
				stringBuilder.Append(rn+t2+"}");
				#endregion SelectMany
				#region TableToList
				//TableToList----------------------------------------------------------------------------------------
				stringBuilder.Append(rn+rn+t2+"///<summary>Converts a DataTable to a list of objects.</summary>");
				stringBuilder.Append(rn+t2+"public static List<"+listTypes[i].Name+"> TableToList(DataTable table) {");
				stringBuilder.Append(rn+t3+"List<"+listTypes[i].Name+"> list"+listTypes[i].Name+"s=new List<"+listTypes[i].Name+">();");
				stringBuilder.Append(rn+t3+"for(int i=0;i<table.Rows.Count;i++) {");
				stringBuilder.Append(rn+t4+listTypes[i].Name+" "+obj+"=new "+listTypes[i].Name+"();");
				int longestField=listFieldInfos.Select(x => x.Name.Length).DefaultIfEmpty(0).Max();
				for(int f = 0;f<listFieldInfos.Count;f++) {
					stringBuilder.Append(rn+t4+obj+"."+listFieldInfos[f].Name.PadRight(longestField,' ')+"= ");
					if(listFieldInfos[f].FieldType.IsEnum) {
						stringBuilder.Append("("+listFieldInfos[f].FieldType.ToString()+")SIn.Int(");//.ToString() instead of .Name to get fully qualified name
					}
					else switch(listFieldInfos[f].FieldType.Name) {
							default:
								throw new ApplicationException("Type not yet supported: "+listFieldInfos[f].FieldType.Name);
							case "Boolean":
								stringBuilder.Append("SIn.Bool  (");
								break;
							case "Color":
								stringBuilder.Append("Color.FromArgb(SIn.Int(");
								break;
							case "DateTime":
								stringBuilder.Append("SIn.DateT (");
								break;
							case "Double":
								stringBuilder.Append("SIn.Double(");
								break;
							case "Int32":
								stringBuilder.Append("SIn.Int   (");
								break;
							case "String":
								stringBuilder.Append("SIn.String(");
								break;
					}
					stringBuilder.Append("table.Rows[i][\""+listFieldInfos[f].Name+"\"].ToString())");
					if(listFieldInfos[f].FieldType.Name=="Color") {
						stringBuilder.Append(")");
					}
					stringBuilder.Append(";");
				}
				stringBuilder.Append(rn+t4+"list"+listTypes[i].Name+"s.Add("+obj+");");
				stringBuilder.Append(rn+t3+"}");
				stringBuilder.Append(rn+t3+"return list"+listTypes[i].Name+"s;");
				stringBuilder.Append(rn+t2+"}");
				#endregion TableToList
				#region Insert
				stringBuilder.Append(rn+rn+t2+"///<summary>Inserts one "+listTypes[i].Name+" into the database.  Returns the new priKey.</summary>");
				stringBuilder.Append(rn+t2+"public static long Insert("+listTypes[i].Name+" "+obj+") {");
				stringBuilder.Append(rn+t3+"string command=\"INSERT INTO "+listTypes[i].Name.ToLower()+" (");
				for(int f=1;f<listFieldInfos.Count;f++) {//starts at 1 to exclude PK
					if(f>1) {
						stringBuilder.Append(",");
					}
					stringBuilder.Append(listFieldInfos[f].Name);
				}
				stringBuilder.Append(") VALUES(\"");
				for(int f=1;f<listFieldInfos.Count;f++) {
					stringBuilder.Append(rn+t4+"+");
					if(listFieldInfos[f].FieldType.IsEnum) {
						stringBuilder.Append("    SOut.Int   ((int)"+obj+"."+listFieldInfos[f].Name+")+\"");
					}
					else switch(listFieldInfos[f].FieldType.Name) {
						default:
							throw new ApplicationException("Type not yet supported: "+listFieldInfos[f].FieldType.Name);
						case "Boolean":
							stringBuilder.Append("    SOut.Bool  ("+obj+"."+listFieldInfos[f].Name+")+\"");
							break;
						case "Color":
							stringBuilder.Append("    SOut.Int   ("+obj+"."+listFieldInfos[f].Name+".ToArgb())+\"");
							break;
						case "DateTime":
							stringBuilder.Append("    SOut.DateT  ("+obj+"."+listFieldInfos[f].Name+")+\"");
							break;
						case "Double":
							stringBuilder.Append("   SOut.Double("+obj+"."+listFieldInfos[f].Name+")+\"");
							break;
						case "Int32":
							stringBuilder.Append("    SOut.Int   ("+obj+"."+listFieldInfos[f].Name+")+\"");
							break;
						case "String":
							stringBuilder.Append("\"'\"+SOut.String("+obj+"."+listFieldInfos[f].Name+")+\"'");
							break;
					}
					if(f<listFieldInfos.Count-1) {
						stringBuilder.Append(",\"");
					}
					else {
						stringBuilder.Append(")\";");
					}
				}
				stringBuilder.Append(rn+t4+obj+"."+listFieldInfos[0].Name+"=Db.NonQ(command,true);");
				stringBuilder.Append(rn+t3+"return "+obj+"."+listFieldInfos[0].Name+";");
				stringBuilder.Append(rn+t2+"}");
				#endregion Insert
				#region Update
				stringBuilder.Append(rn+rn+t2+"///<summary>Updates one "+listTypes[i].Name+" in the database.</summary>");
				stringBuilder.Append(rn+t2+"public static void Update("+listTypes[i].Name+" "+obj+") {");
				stringBuilder.Append(rn+t3+"string command=\"UPDATE "+listTypes[i].Name.ToLower()+" SET \"");
				for(int f=1;f<listFieldInfos.Count;f++) {
					stringBuilder.Append(rn+t4+"+\""+listFieldInfos[f].Name.PadRight(longestField,' ')+"= ");
					if(listFieldInfos[f].FieldType.IsEnum) {
						stringBuilder.Append(" \"+SOut.Int   ((int)"+obj+"."+listFieldInfos[f].Name+")+\"");
					}
					else switch(listFieldInfos[f].FieldType.Name) {
						default:
							throw new ApplicationException("Type not yet supported: "+listFieldInfos[f].FieldType.Name);
						case "Boolean":
							stringBuilder.Append(" \"+SOut.Bool  ("+obj+"."+listFieldInfos[f].Name+")+\"");
							break;
						case "Color":
							stringBuilder.Append(" \"+SOut.Int   ("+obj+"."+listFieldInfos[f].Name+".ToArgb())+\"");
							break;
						case "DateTime":
							stringBuilder.Append(" \"+SOut.DateT  ("+obj+"."+listFieldInfos[f].Name+")+\"");
							break;
						case "Double":
							stringBuilder.Append(" \"+SOut.Double("+obj+"."+listFieldInfos[f].Name+")+\""); 
							break;
						case "Int32":
							stringBuilder.Append(" \"+SOut.Int   ("+obj+"."+listFieldInfos[f].Name+")+\"");
							break;
						case "String":
							stringBuilder.Append("'\"+SOut.String("+obj+"."+listFieldInfos[f].Name+")+\"'");
							break;
					}
					if(f<listFieldInfos.Count-1){
						stringBuilder.Append(",");
					}
					stringBuilder.Append(" \"");
				}
				stringBuilder.Append(rn+t4+"+\"WHERE "+listFieldInfos[0].Name+" = \"+SOut.Int("+obj+"."+listFieldInfos[0].Name+");");
				stringBuilder.Append(rn+t3+"Db.NonQ(command);");
				stringBuilder.Append(rn+t2+"}");
				#endregion Update
				#region Closing braces
				stringBuilder.Append(@"
	}
}");
				#endregion Closing braces
				string filePath=Path.Combine(crudDir,listTypes[i].Name+"Crud.cs");
				File.WriteAllText(filePath,stringBuilder.ToString());
				Close();
			}
		}
	}
}
